config/routes.rb
Scheduler::Application.routes.draw do

  root :to => 'pages#home'
  
  resources :leagues do
    member do
      get 'teams'
      get 'fields'
      get 'past_seasons'
      get 'contacts'
      get 'rules'  
    end
  end
  
  resources :users do
    member do
      get 'my_schedule'     
      get 'teams'
      get 'leagues'
    end
  end
  match '/signup' => 'users#new'
  
  resources :contracts, :only => [:new, :create, :show, :destroy]
  
  resources :sessions, :only => [:new, :create, :destroy]
  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  
  resources :seasons, :teams, :schedules, :fields, :matches, :divisions
  
end 

app/models/appearance.rb
class Appearance < ActiveRecord::Base
  
  belongs_to :match
  belongs_to :team
  
end

app/models/cap.rb
class Cap < ActiveRecord::Base
  
  belongs_to :match
  belongs_to :user
  
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  
# Association
  belongs_to :user
  belongs_to :team
  
end

app/models/division.rb
class Division < ActiveRecord::Base
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  
#Associations
  belongs_to :season
  belongs_to :team
  
end

app/models/field.rb
class Field < ActiveRecord::Base
  
# Associations
  has_many :matches
    
end

app/models/heuristic.rb
class Heuristic < ActiveRecord::Base

# Associations  
  has_many :schedules
  
end

app/models/league.rb
class League < ActiveRecord::Base
  
  has_many :seasons
  
end

app/models/match.rb
class Match < ActiveRecord::Base

# Associations
  belongs_to :schedule
  belongs_to :field
  
  has_many :appearances
  has_many :teams, :through => :appearances

  has_many :caps
  has_many :users, :through => :caps

# Methods

def team_names
  team_names = [self.teams.to_a[0]["name"], self.teams.to_a[1]["name"]]
end

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

# Associations
  has_many :matches
  belongs_to :heuristic  
  belongs_to :season

# Callbacks

# Methods

def list_team_names
  team_list = self.teams
  teams = []
  team_list.each do |team|
    teams.push(team.name)
  end
  return teams
end

end

app/models/season.rb
class Season < ActiveRecord::Base
  
#Associations
  belongs_to :leagues
  has_many :schedules
  
  has_many :enrollments
  has_many :teams, :through => :enrollments
  
end

app/models/team.rb
class Team < ActiveRecord::Base

# Associations
  has_many :contracts
  has_many :users, :through => :contracts
  
  has_many :appearances
  has_many :matches, :through => :appearances
  
  has_many :enrollments
  has_many :seasons, :through => :enrollments
  
end

app/models/user.rb
class User < ActiveRecord::Base
# Attributes
  attr_accessor :password #creates a virtual attr :password
  attr_accessible :name, :email, :password, :password_confirmation, :age,
                  :admin, :player, :coach, :team_manager, :league_manager

# Associations
  has_many :contracts
  has_many :teams, :through => :contracts
  
  has_many :caps
  has_many :matches, :through => :caps
  
  has_many :assignments
  has_many :roles, :through => :assignments
  
# Validations
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
                   :length => { :maximum => 50 }
  
  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
                    
  validates :password, :presence => true,
                       :length => { :within => 3..40 },
                       :confirmation => true  
                       # automatically creates virtual attr password_confirmation

# Callbacks

  before_save :encrypt_password

# Public Methods

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  # similar to code above, but more idiomatically ruby (replaces if-ifelse)
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
# Private Methods

private

  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end
  
  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end
  
  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end
  
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end

end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/partials/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
      <div class="container-fluid">
     
				<!-- Collapse -->
 				<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        	<span class="icon-bar"></span>
        	<span class="icon-bar"></span>
        	<span class="icon-bar"></span>
      	</a>
				
<!-- Brand Name -->
      	<a class="brand" href="/">Scheduler Home</a>

<!-- Nav Tabs -->
      	<div class="container-fluid nav-collapse">
        	<ul class="nav">	
						<% if logged_in? %>
							<li><%= link_to "My Profile", user_path(@current_user)%></li>
							<li><%= link_to "My Schedule", my_schedule_user_path(@current_user)%></li>
							<li class="dropdown">					
								<a class="dropdown-toggle" data-toggle="dropdown" href="#">
									Teams<b class="caret"></b></a>
									
<!-- Team Menu Bar -->
						 		<ul class="dropdown-menu">
						  		<li><%= link_to "My Teams", teams_user_path(@current_user) %></li>
						  		<li><%= link_to "Find a Team", teams_path %></li>
						
									<li class="divider"></li>	
									<% if current_user.player == true %>
						  			<li><%= link_to "Join a new team" %></li>
									<% end %>

						  	</ul>
							</li>
							
<!-- League Menu Bar -->
							<li class="dropdown">					
								<a class="dropdown-toggle" data-toggle="dropdown" href="#">
									Leagues<b class="caret"></b></a>
						 		<ul class="dropdown-menu">
						  		<li><%= link_to "My Leagues", leagues_user_path(@current_user) %></li>
						  		<li><%= link_to "Find a League", leagues_path %></li>		
						
									<li class="divider"></li>
									<% if current_user.player == true %>
						  			<li><%= link_to "Individually join in a league", leagues_user_path(@current_user) %></li>
									<% end %>
								</ul>
					  
							</li>
							
<!-- Management Tool Menu Bar -->
							<li class="dropdown">					
								<a class="dropdown-toggle" data-toggle="dropdown" href="#">
									Management Tools<b class="caret"></b></a>
						 		<ul class="dropdown-menu">
									<li>Team Management Tools</li>
									<li class="divider"></li>
									<% if current_user.team_manager == true %>
										<li><%= link_to "Enroll a team in a new league", new_contract_path %></li>
										<li><%= link_to "Contract new players", new_contract_path %>
						  			<li><%= link_to "Create a new team", new_team_path %></li>
										<li></br> </li>
									<% end %>
									
									<% if current_user.league_manager == true %>
										<li>League Management Tools</li>
										<li class="divider"></li>
										<li><%= link_to "Add a News story", leagues_path %>
										<li><%= link_to "Create a league schedule", new_schedule_path %>
										<li><%= link_to "Manage league teams", new_team_path %></li>
						  			<li><%= link_to "Manage league fields", new_team_path %></li>
									<% end %>
						  	</ul>
							</li>
						<% end %>		
        </ul>

<!-- Tabs pulled to the Right -->
				<ul class="nav pull-right">
					<% if logged_in? %>
						<li><%= link_to "Log Out", logout_path, :method => :delete %></li>
						<li><%= link_to 'New User?', signup_path %>		
					<% else %>
						<li><%= link_to "Log In", login_path %></li>
						<li><%= link_to 'New User?', signup_path %></li>
					<% end %>
				<ul>
					
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </div><!--/.navbar-inner -->
</div>

app/views/partials/_secondary_nav.html.erb
<div class="page-header">
	<h1><%= @league.name %></h1>
</div>

<ul class="nav nav-pills">
	<li class="active"><%= link_to league_path(@league) do %>
		  <i class="icon-home icon-white"></i> Home
		<% end %></li>
	<li class="active"><%= link_to rules_league_path(@league) do %>
			  <i class="icon-flag icon-white"></i> Rules
			<% end %></li>
	<li class="active"><%= link_to schedule_path(@current_schedule) do %>
		  <i class="icon-calendar icon-white"></i> Schedule
		<% end %></li>
	<li class="active"><%= link_to  teams_league_path(@league) do %>
		 	<i class="icon-user icon-white"></i> Teams
			<% end %></li>
	<li class="active"><%= link_to  fields_league_path(@league) do %>
			<i class="icon-picture icon-white"></i> Fields
	<% end %></li>
	<li class="active"><%= link_to past_seasons_league_path(@league) do %>
		  <i class="icon-th icon-white"></i> Past Seasons
			<% end %></li>
	<li class="active"><%= link_to contacts_league_path(@league) do %>
			<i class="icon-envelope icon-white"></i> Contacts
			<% end %></li>
</ul>