config/routes.rb
Scheduler::Application.routes.draw do

  root :to => 'pages#home'
  
  resources :leagues do
    member do
      get 'teams'
      get 'fields'
      get 'past_seasons'
      get 'contacts'
      get 'rules'  
    end
  end
  
  resources :users do
    member do
      get 'my_schedule'     
      get 'teams'
      get 'leagues'
    end
  end
  match '/signup' => 'users#new'
  
  resources :contracts, :only => [:new, :create, :show, :destroy]
  
  resources :sessions, :only => [:new, :create, :destroy]
  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  
  resources :seasons, :teams, :schedules, :fields, :matches, :divisions
  
end 

app/models/appearance.rb
class Appearance < ActiveRecord::Base
  
  belongs_to :match
  belongs_to :team
  
end

app/models/cap.rb
class Cap < ActiveRecord::Base
  
  belongs_to :match
  belongs_to :user
  
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  
# Association
  belongs_to :user
  belongs_to :team
  
end

app/models/division.rb
class Division < ActiveRecord::Base
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  
#Associations
  belongs_to :season
  belongs_to :team
  
end

app/models/field.rb
class Field < ActiveRecord::Base
  
# Associations
  has_many :matches
    
end

app/models/heuristic.rb
class Heuristic < ActiveRecord::Base

# Associations  
  has_many :schedules
  
end

app/models/league.rb
class League < ActiveRecord::Base
  
  has_many :seasons
  
end

app/models/match.rb
class Match < ActiveRecord::Base

# Associations
  belongs_to :schedule
  belongs_to :field
  
  has_many :appearances
  has_many :teams, :through => :appearances

  has_many :caps
  has_many :users, :through => :caps

# Methods

def team_names
  team_names = [self.teams.to_a[0]["name"], self.teams.to_a[1]["name"]]
end

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

# Associations
  has_many :matches
  belongs_to :heuristic  
  belongs_to :season

# Callbacks

# Methods

def list_team_names
  team_list = self.teams
  teams = []
  team_list.each do |team|
    teams.push(team.name)
  end
  return teams
end

end

app/models/season.rb
class Season < ActiveRecord::Base
  
#Associations
  belongs_to :leagues
  has_many :schedules
  
  has_many :enrollments
  has_many :teams, :through => :enrollments
  
end

app/models/team.rb
class Team < ActiveRecord::Base

# Associations
  has_many :contracts
  has_many :users, :through => :contracts
  
  has_many :appearances
  has_many :matches, :through => :appearances
  
  has_many :enrollments
  has_many :seasons, :through => :enrollments
  
end

app/models/user.rb
class User < ActiveRecord::Base
# Attributes
  attr_accessor :password #creates a virtual attr :password
  attr_accessible :name, :email, :password, :password_confirmation, :age,
                  :admin, :player, :coach, :team_manager, :league_manager

# Associations
  has_many :contracts
  has_many :teams, :through => :contracts
  
  has_many :caps
  has_many :matches, :through => :caps
  
  has_many :assignments
  has_many :roles, :through => :assignments
  
# Validations
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
                   :length => { :maximum => 50 }
  
  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
                    
  validates :password, :presence => true,
                       :length => { :within => 3..40 },
                       :confirmation => true  
                       # automatically creates virtual attr password_confirmation

# Callbacks

  before_save :encrypt_password

# Public Methods

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  # similar to code above, but more idiomatically ruby (replaces if-ifelse)
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
# Private Methods

private

  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end
  
  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end
  
  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end
  
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController


  def index
    @schedules = Schedule.all
  end

  def show
    @schedule = Schedule.find(params[:id])
    @matches = @schedule.matches
    @league = League.find(Season.find(@schedule.season_id).league_id)
  end

  def new
    @schedule = Schedule.new
  end
    
  def create 
    
    @schedule = Schedule.new(params[:schedule])    
    round_robin(@schedule)
    
    if @schedule.save
      redirect_to @schedule
    end
  end

  def update
    @schedule = Schedule.find(params[:id])

  respond_to do |format|
    if @schedule.update_attributes(params[:schedule])
      format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
    else
      format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    
    respond_to do |format|
      format.html { redirect_to schedules_url }
    end
  end 
end

#    def edit
#      @schedule = Schedule.find(params[:id])
#    end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper

# Helper methods are automatically available to views.  To make them available to controllers
# add them to the application_controller with Include SchedulesHelper
  
  def round_robin(schedule)
    teams = schedule.team_ids
    x = 0
    while x < teams.length
      y = x + 1    
      while y < teams.length
        team1 = Team.find(teams[x])
        team2 = Team.find(teams[y])
        @match = Match.create
        @match.teams.push(team1)
        @match.teams.push(team2)
        @schedule.matches.push(@match)
        y += 1
      end
      x += 1
    end
  end

  def random(schedule, n)
    teams = schedule.team_ids
    i = 1

    while i <= n
    x = rand(n)
    y = rand(n)

    #need to add a way to make sure each team is getting matches

    unless x == y
        team1 = Team.find(teams[x])
        team2 = Team.find(teams[y])
        @match = Match.create
        @match.teams.push(team1)
        @match.teams.push(team2)
        @schedule.matches.push(@match)
        i += 1
      end
    end
  end
  
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def login(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user # defines the current user for the session
  end
  
  # explicit setter method
  def current_user=(user)
    @current_user = user
  end
  
  # @current_user = @current_user or user_from_remember_token
  # || is the or symbol.  The first true statement satisfies the condition.
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def logout
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def deny_access
    store_location
    flash[:notice] = "Please Log In to view this page."
    redirect_to login_path
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || [default])
    clear_return_to
  end
  
  def current_user?(user)
    user == current_user
  end
  
private
# methods available to the sessions helper only
  
  def user_from_remember_token
    User.authenticate_with_salt(*remember_token) # remember_token = [id, salt]
  end
  
  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end
  
  def store_location
    session[:return_to] = request.fullpath
  end
  
  def clear_return_to
    session[:return_to] = nil
  end
  
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/schedules/_scheduling_form.html.erb
<h2> Use the options below to create a schedule </h2>

<%= simple_form_for @schedule, :html => { :class => 'form-vertical' } do |f| %>
  <%= f.input :name, :label => "League Name" %>
  <%= f.input :manager, :label => "League Manager's Name" %>
  <%= f.association :heuristic, :as => :radio_buttons %>
	<%= f.association :teams, :as => :check_boxes %>


  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                schedules_path, :class => 'btn' %>
  </div>
<% end %>

app/views/schedules/_secondary_form.html.erb
<h2> Fill out these Scheduling Options </h2>

<%= simple_form_for @schedule, :html => { :class => 'form-vertical' } do |f| %>
	<%= f.association :teams, :as => :check_boxes %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                schedules_path, :class => 'btn' %>
  </div>

<% end %>

app/views/schedules/index.html.erb
<%- model_class = Schedule.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:manager) %></th>
      <th><%= model_class.human_attribute_name(:heuristic_id) %></th>
      <th>Teams</th>
      <th>Matches</th>


      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= link_to schedule.id, schedule_path(schedule) %></td>
        <td><%= schedule.name %></td>
        <td><%= schedule.manager %></td>
        <td><%= schedule.heuristic_id %></td>
        <td></td>
        <td></td>
        <td>
	        <%= link_to t('.show', :default => t("helpers.links.show")),
                      schedule_path(schedule), :class => 'btn btn-mini' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_schedule_path(schedule), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      schedule_path(schedule),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_schedule_path,
            :class => 'btn btn-primary' %>

app/views/schedules/new.html.erb
<%- model_class = @schedule.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>

<%= render :partial => 'scheduling_form' %>

app/views/schedules/secondary_options.html.erb
<%- model_class = @schedule.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:name) %>:</strong><br>
  <%= @schedule.name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:manager) %>:</strong><br>
  <%= @schedule.manager %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:heuristic_id) %>:</strong><br>
  <%= @schedule.heuristic_id %>
</p>

<%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_schedule_path(@schedule), :class => 'btn' %>


<%= render "secondary_form" %>

app/views/schedules/show.html.erb
<%= render 'partials/secondary_nav'%>

<!-- Table display of all Matches in the League -->

<%- model_class = Match.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
			<th>Match Status</th>
      <th>Team 1</th>
      <th>Score</th>
      <th>Team 2</th>
      <th>Score</th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= link_to match.id, match_path(match) %></td>
				<td><% if match.played %>
								<%= 'played' %>
							<% else %>
								<%= 'to be played' %>
							<% end %>
				</td>
        <td><%= link_to match.teams[0].name, team_path(match.teams[0].id) %></td>
        <td><%= match.score1%></td>
				<td><%= link_to match.teams[1].name, team_path(match.teams[1].id) %></td>
				<td><%= match.score2%></td>
        <td>
	        <%= link_to t('.show', :default => t("helpers.links.show")),
                      match_path(match), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- Table display of all Schedule Information -->
</br>
<div class="row-fluid">
	<div class="span12">
		<h2>Schedule Creation Details</h2>
		</br>
		<p><strong>Schedule Name:</strong> <%= @schedule.name %></p>
		<p><strong>Manager:</strong> <%= @schedule.manager %></p>
		<p><strong>Heuristic:</strong> <%= @schedule.heuristic.name %></p>
	</div>
</div>