config/routes.rb
Scheduler::Application.routes.draw do

  root :to => 'pages#home'
  
  resources :leagues do
    member do
      get 'teams'
      get 'fields'
      get 'past_seasons'
      get 'contacts'
      get 'rules'  
    end
  end
  
  resources :users do
    member do
      get 'my_schedule'     
      get 'teams'
      get 'leagues'
    end
  end
  match '/signup' => 'users#new'
  
  resources :contracts, :only => [:new, :create, :show, :destroy]
  
  resources :sessions, :only => [:new, :create, :destroy]
  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  
  resources :seasons, :teams, :schedules, :fields, :matches, :divisions
  
end 

app/models/appearance.rb
class Appearance < ActiveRecord::Base
  
  belongs_to :match
  belongs_to :team
  
end

app/models/cap.rb
class Cap < ActiveRecord::Base
  
  belongs_to :match
  belongs_to :user
  
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  
# Association
  belongs_to :user
  belongs_to :team
  
end

app/models/division.rb
class Division < ActiveRecord::Base
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  
#Associations
  belongs_to :season
  belongs_to :team
  
end

app/models/field.rb
class Field < ActiveRecord::Base
  
# Associations
  has_many :matches
    
end

app/models/heuristic.rb
class Heuristic < ActiveRecord::Base

# Associations  
  has_many :schedules
  
end

app/models/league.rb
class League < ActiveRecord::Base
  
  has_many :seasons
  
end

app/models/match.rb
class Match < ActiveRecord::Base

# Associations
  belongs_to :schedule
  belongs_to :field
  
  has_many :appearances
  has_many :teams, :through => :appearances

  has_many :caps
  has_many :users, :through => :caps

# Methods

def team_names
  team_names = [self.teams.to_a[0]["name"], self.teams.to_a[1]["name"]]
end

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

# Associations
  has_many :matches
  belongs_to :heuristic  
  belongs_to :season

# Callbacks

# Methods

def list_team_names
  team_list = self.teams
  teams = []
  team_list.each do |team|
    teams.push(team.name)
  end
  return teams
end

end

app/models/season.rb
class Season < ActiveRecord::Base
  
#Associations
  belongs_to :leagues
  has_many :schedules
  
  has_many :enrollments
  has_many :teams, :through => :enrollments
  
end

app/models/team.rb
class Team < ActiveRecord::Base

# Associations
  has_many :contracts
  has_many :users, :through => :contracts
  
  has_many :appearances
  has_many :matches, :through => :appearances
  
  has_many :enrollments
  has_many :seasons, :through => :enrollments
  
end

app/models/user.rb
class User < ActiveRecord::Base
# Attributes
  attr_accessor :password #creates a virtual attr :password
  attr_accessible :name, :email, :password, :password_confirmation, :age,
                  :admin, :player, :coach, :team_manager, :league_manager

# Associations
  has_many :contracts
  has_many :teams, :through => :contracts
  
  has_many :caps
  has_many :matches, :through => :caps
  
  has_many :assignments
  has_many :roles, :through => :assignments
  
# Validations
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
                   :length => { :maximum => 50 }
  
  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
                    
  validates :password, :presence => true,
                       :length => { :within => 3..40 },
                       :confirmation => true  
                       # automatically creates virtual attr password_confirmation

# Callbacks

  before_save :encrypt_password

# Public Methods

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  # similar to code above, but more idiomatically ruby (replaces if-ifelse)
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
# Private Methods

private

  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end
  
  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end
  
  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end
  
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end

end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  # GET /fields
  # GET /fields.json
  def index
    @fields = Field.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fields }
    end
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
    @field = Field.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @field }
    end
  end

  # GET /fields/new
  # GET /fields/new.json
  def new
    @field = Field.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @field }
    end
  end

  # GET /fields/1/edit
  def edit
    @field = Field.find(params[:id])
  end

  # POST /fields
  # POST /fields.json
  def create
    @field = Field.new(params[:field])

    respond_to do |format|
      if @field.save
        format.html { redirect_to @field, notice: 'Field was successfully created.' }
        format.json { render json: @field, status: :created, location: @field }
      else
        format.html { render action: "new" }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fields/1
  # PUT /fields/1.json
  def update
    @field = Field.find(params[:id])

    respond_to do |format|
      if @field.update_attributes(params[:field])
        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    @field = Field.find(params[:id])
    @field.destroy

    respond_to do |format|
      format.html { redirect_to fields_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def login(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user # defines the current user for the session
  end
  
  # explicit setter method
  def current_user=(user)
    @current_user = user
  end
  
  # @current_user = @current_user or user_from_remember_token
  # || is the or symbol.  The first true statement satisfies the condition.
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def logout
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def deny_access
    store_location
    flash[:notice] = "Please Log In to view this page."
    redirect_to login_path
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || [default])
    clear_return_to
  end
  
  def current_user?(user)
    user == current_user
  end
  
private
# methods available to the sessions helper only
  
  def user_from_remember_token
    User.authenticate_with_salt(*remember_token) # remember_token = [id, salt]
  end
  
  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end
  
  def store_location
    session[:return_to] = request.fullpath
  end
  
  def clear_return_to
    session[:return_to] = nil
  end
  
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fields/_form.html.erb
<%= simple_form_for @field, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :field_num %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                fields_path, :class => 'btn' %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<%- model_class = @field.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/fields/index.html.erb
<%- model_class = Field.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:field_num) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @fields.each do |field| %>
      <tr>
        <td><%= link_to field.id, field_path(field) %></td>
        <td><%= field.name %></td>
        <td><%= field.field_num %></td>
        <td><%=l field.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_field_path(field), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      field_path(field),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_field_path,
            :class => 'btn btn-primary' %>

app/views/fields/new.html.erb
<%- model_class = @field.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/fields/show.html.erb
<%- model_class = @field.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:name) %>:</strong><br>
  <%= @field.name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:field_num) %>:</strong><br>
  <%= @field.field_num %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              fields_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_field_path(@field), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              field_path(@field),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>